[versions]
hubdle = "0.5.0-alpha.8"
jgit = "6.5.0.202303070854-r"

[libraries]
eclipse-jgit-eclipseJgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }

[plugins]
javiersc-hubdle = { id = "com.javiersc.hubdle", version.ref = "hubdle" }
