[versions]
coroutines = "1.5.2"
javierscKotlinStdlib = "0.1.0-alpha.1"
jgit = "5.13.0.202109080827-r"
kotest = "4.6.3"
semanticVersioning = "0.1.0-beta.6"

[libraries]
javiersc-kotlin-kotlinStdlib = { group = "com.javiersc.kotlin", name = "kotlin-stdlib", version.ref = "javierscKotlinStdlib" }
javiersc-semanticVersioning-semanticVersioningCore = { group = "com.javiersc.semantic-versioning", name = "semantic-versioning-core", version.ref = "semanticVersioning" }
jetbrains-kotlin-kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test" }
jetbrains-kotlinx-kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
eclipse-jgit-eclipseJgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
kotest-kotestAssertionsCore = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
