[versions]
hubdle = "0.2.0-alpha.43"
jgit = "6.3.0.202209071007-r"
semverCore = "0.1.0-beta.10"

[libraries]
javiersc-semver-semverCore = { module = "com.javiersc.semver:semver-core", version.ref = "semverCore" }
eclipse-jgit-eclipseJgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }

[plugins]
javiersc-hubdle = { id = "com.javiersc.hubdle", version.ref = "hubdle" }
