site_name: 'SemVer Gradle Plugin'
site_description: 'Gradle plugin to configure automatically the projects version based on git tags'
site_author: 'Javier Segovia Córdoba'
remote_branch: gh-pages

repo_name: 'semver-gradle-plugin'
repo_url: 'https://github.com/JavierSegoviaCordoba/semver-gradle-plugin'

copyright: 'Copyright &copy; 2021 Javier Segovia Córdoba'

theme:
  name: 'material'
  language: 'en'
  favicon: 'assets/favicon.png'
  logo: 'assets/logo.svg'
  font:
    text: 'Fira Sans'
    code: 'JetBrains Mono'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'white'
      accent: 'white'
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: 'indigo'
      accent: 'light blue'
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
nav:
  - Overview: index.md
  - Examples:
    - All projects: examples/ALL_PROJECTS.md

plugins:
  - search

markdown_extensions:
  - admonition
  - smarty
  - codehilite:
      guess_lang: false
      linenums: True
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - tables

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JavierSegoviaCordoba
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/JavierSegoviaCo

extra_css:
  - css/all.css
