name: build-kotlin-dispatcher

on:
  workflow_dispatch:
    inputs:
      gradle-args:
        description: 'Gradle args for every step'
        default: ''
        required: false
      publish-all-docs:
        description: 'Publish all docs instead of only API docs and reports'
        required: false
        default: false
        type: boolean

jobs:
  build:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/build-kotlin.yaml@hubdle-5
    with:
      gradle-args: '${{ github.event.inputs.gradle-args }}'
      allow-github-actor-bots: false
      code-coverage-report: true
      publish-all-docs: '${{ github.event.inputs.publish-all-docs }}'
    secrets: inherit
