name: dump-api

on:
  workflow_dispatch:

jobs:
  dump-api:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/dump-api.yaml@22c3dce85094790803f899aa8a405b3c186e26b9 # main
    with:
      restore-kotlin-native-cache: false
    secrets: inherit
