name: dump-api

on:
  workflow_dispatch:

jobs:
  dump-api:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/dump-api.yaml@4fed19bced81f4d1690fab4679e6453c774b0909 # main
    with:
      restore-kotlin-native-cache: false
    secrets: inherit
