name: dump-api

on:
  workflow_dispatch:

jobs:
  dump-api:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/dump-api.yaml@b3f4c6f534709f4429658f3e1441243032e48b14 # main
    with:
      restore-kotlin-native-cache: false
    secrets: inherit
