name: initial-setup

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Project name used for docs or POM data'
        default: 'Kotlin Template'
        required: true
      description:
        description: 'Project description used for docs or POM data'
        default: 'A template which allow to create Kotlin projects'
        required: true
      repo:
        description: 'Project repo used for docs or POM data (`https://github.com/JavierSegoviaCordoba/[this]`)'
        default: 'kotlin-template'
        required: true
      maven_name:
        description: 'Project id behind the group to generate the groupId (`group.[THIS]:artifactId:version`)'
        default: 'template'
        required: true
      main:
        description: 'Main project maven name (`groupId:[THIS]:version`)'
        default: 'library'
        required: true
      machines:
        description: 'Virtual environment used in GitHub Actions workflows'
        default: 'macos-latest, ubuntu-latest, windows-latest'
        required: true
      publish-gradle_plugin_portal:
        description: 'Enable publishing to Gradle Plugin Portal in GitHub Actions workflows'
        default: 'false'
        required: true
      publish-jetbrains-marketplace:
        description: 'Enable publishing to JetBrains marketplace GitHub Actions workflows'
        default: 'false'
        required: true

jobs:
  initial-setup:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: '${{ secrets.TOKEN_GITHUB_ACTION }}'

      - name: Clean up TODOs
        run: kotlin initial-setup.main.kts "name = ${{ github.event.inputs.name }}" "description = ${{ github.event.inputs.description }}" "repo = ${{ github.event.inputs.repo }}" "maven_name = ${{ github.event.inputs.maven_name }}" "main = ${{ github.event.inputs.main }}" "machines = ${{ github.event.inputs.machines }}" "gradle_plugin_portal = ${{ github.event.inputs.gradle_plugin_portal }}"

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff
          git add .
          git commit -m "Initial setup" -a

      - name: Push
        run: git push
