name: publish

on:
  push:
    tags:
      - '**'

jobs:
  github-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0

      - name: Set pre-release
        shell: bash
        id: pre_release
        run: |
          if [[ ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }} ]]
          then
            echo ::set-output name=is_pre_release::true
          else
            echo ::set-output name=is_pre_release::false
          fi

      - name: Set up Java
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Build
        uses: gradle/gradle-build-action@v2.0-beta.7
        with:
          arguments: build

      - name: Release
        uses: anton-yurchenko/git-release@v4.1.2
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          DRAFT_RELEASE: true
          PRE_RELEASE: '${{ steps.pre_release.outputs.is_pre_release }}'
          CHANGELOG_FILE: 'CHANGELOG.md'
          ALLOW_EMPTY_CHANGELOG: false
